include: package:lints/core.yaml

analyzer:
  language:
    strict-casts: false

linter:
  rules:
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - unnecessary_const
    - unnecessary_new
